<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addItemsLink</name>
   <tag></tag>
   <elementGuidId>1a77e499-e097-495c-bffb-7e75c4168539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;confirmation-page&quot;]/div/div/div[5]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;confirmation-page&quot;]/div/div/div[5]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
