<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_new_qty</name>
   <tag></tag>
   <elementGuidId>b1e265da-34c9-4071-8979-8b2e0d4a3887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='quick-look-inner']/div/div/add-to-cart/div/div[@class='add-to-cart-form']/div[@class='qty']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
