<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MicrositeTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f8f9005f-61f0-4c5e-8f8a-7e004b111259</testSuiteGuid>
   <testCaseLink>
      <guid>f8868181-fba7-4ccb-92e7-f81ad4774412</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/createShow</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2ce6578b-c9c6-4cfb-bd38-4f9b3e91b589</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/virtualShowData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fa34b38-6b70-4e86-bfb8-8af5df243999</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8df15ebe-7734-4c25-bae3-a4f6128a752f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93f310b6-cb8e-4bbd-b681-927314c49b49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6b272fb-272d-46df-a56e-7ed105405f34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a350b21-00ef-452c-9a7e-afe1b44f0681</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4245740-0c7c-471a-beaa-456df1866d16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9497093f-b7a0-4b10-9ad3-7dce8baf6581</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c925dc7d-3bdf-4cdf-9649-615241c114e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/micrositeRSVPValidUser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>572323f7-6b8e-4883-86ff-2b8d05fc8cf6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71c91759-1b13-4f1c-a097-bd689290afa1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
