<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>completeProfileLater</name>
   <tag></tag>
   <elementGuidId>f460a19e-3dc9-4252-a259-caa2196fc448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;page-&quot;]/div[2]/overlay-container-component/div/app-complete-your-profile-overlay/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;page-&quot;]/div[2]/overlay-container-component/div/app-complete-your-profile-overlay/div/div/div/div[2]/div</value>
   </webElementProperties>
</WebElementEntity>
