<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>carouselFav</name>
   <tag></tag>
   <elementGuidId>7a659adc-71dd-4c9b-b069-9e8589b870ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;page&quot;]/show-microsite/div/div/div[1]/app-carousel/div/div/div[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;page&quot;]/show-microsite/div/div/div[1]/app-carousel/div/div/div[1]/a</value>
   </webElementProperties>
</WebElementEntity>
