<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>playVideosButton</name>
   <tag></tag>
   <elementGuidId>966c0b3d-f75b-4c89-b2e7-93969d14cf89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;main-container&quot;]/div/div[3]/div[1]/div/div[1]/app-video-conference-phase-control/div/span[2]/span/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;main-container&quot;]/div/div[3]/div[1]/div/div[1]/app-video-conference-phase-control/div/span[2]/span/button</value>
   </webElementProperties>
</WebElementEntity>
