<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>EditOrderSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c3825cdf-bbd9-4f5b-8eec-503fc8af5efd</testSuiteGuid>
   <testCaseLink>
      <guid>8683407e-edc5-4ff7-ae2c-dd0b7fe7aa6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/EditOrder-V/rsEditOrderSimple</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff96322f-9065-41b9-8d3c-b5edaa01181e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d38d882-3cac-4d95-85d5-609dd641fac6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/EditOrder-V/rsEditOrderDonation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aeaeeed0-c611-41bc-bd38-d860cb378d2d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f180958-7c6c-4edf-9a9d-fdf6bb21c766</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/EditOrder-V/rsEditOrderGiftCard</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f83a9981-7707-4104-aad1-101986952818</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87125a85-7ff1-4727-9d1d-05ea01830a1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/EditOrder-V/rsEditOrderPartialShip</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef585920-c073-4a47-89e3-5359fbc25c12</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2420ec8c-ac1c-4b2d-a197-3cb740ab489d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/EditOrder-V/rsEditOrderRS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>137e9e5c-36d1-42a8-a382-da49a12aab59</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f4e87c3-3437-4f46-b854-09b2af482d3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/EditOrder-V/rsEditOrderAddNewItems</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
