<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>EditOrderTestSuit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>41f992da-554c-4b18-8e13-3aeb315b05cf</testSuiteGuid>
   <testCaseLink>
      <guid>ae372238-415d-45d9-9044-a631bb52866f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/editOrder/rsEditOrderSimple</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff96322f-9065-41b9-8d3c-b5edaa01181e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41ec1bdd-e379-48cd-b3b1-e87b1f825e7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/editOrder/rsEditOrderDonation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aeaeeed0-c611-41bc-bd38-d860cb378d2d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c5cbe559-c827-4fd0-90fa-62181b1acd86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/editOrder/rsEditOrderGiftCard</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f83a9981-7707-4104-aad1-101986952818</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7d88048-14ad-4125-8c63-0b90b73711e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/editOrder/rsEditOrderPartialShip</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef585920-c073-4a47-89e3-5359fbc25c12</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62710e37-a65b-40ad-b6ea-35c1c0c5823e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/editOrder/rsEditOrderRS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>137e9e5c-36d1-42a8-a382-da49a12aab59</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
