<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Jackets_check</name>
   <tag></tag>
   <elementGuidId>178c93ec-a108-4056-940a-c8f606fda121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mm-0']/div/div/questionnaire-root/app-questionnaire/div/div/app-questionnaire-my-style-product-rs/div/div/div/div/div[6]/app-my-style-product-question/div/div[4]/div/label/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mm-0&quot;)/div[1]/div[@class=&quot;cointainer&quot;]/questionnaire-root[1]/app-questionnaire[@class=&quot;ng-tns-c9-0 ng-star-inserted&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;inner-content ng-trigger ng-trigger-routerAnimations&quot;]/app-questionnaire-my-style-product-rs[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;questionnaire-page&quot;]/div[@class=&quot;scroll-holder&quot;]/div[@class=&quot;swiper-container scroll-field&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide questionnaire-content ng-star-inserted&quot;]/app-my-style-product-question[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3 col-md-3 product-image-holder col-xs-6 ng-star-inserted&quot;]/div[@class=&quot;radio-button ng-star-inserted&quot;]/label[@class=&quot;radio-label&quot;]/div[@class=&quot;check&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//main[@id='mm-0']/div/div/questionnaire-root/app-questionnaire/div/div/app-questionnaire-my-style-product-rs/div/div/div/div/div[6]/app-my-style-product-question/div/div[4]/div/label/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jackets'])[4]/following::div[17]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dresses'])[3]/following::div[28]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='continue'])[1]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='style'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[6]/app-my-style-product-question/div/div[4]/div/label/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
