<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_payment_options_new_cc</name>
   <tag></tag>
   <elementGuidId>c4833ba2-b177-4cf6-a8a4-215a15139462</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='checkoutpaymentform']/div/div[@class='payment-method']/ul/li/select[@name='payment-first']/option[@value='addNewCC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
