<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_payment_options_select</name>
   <tag></tag>
   <elementGuidId>791ea1d9-f757-48cc-83c1-cfa899f4b6c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='checkoutpaymentform']/div/div[@class='payment-method']/ul/li/select[@name='payment-first']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
