<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_8</name>
   <tag></tag>
   <elementGuidId>d238c090-a582-4a0a-864f-76616b9bae62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mm-0']/div/div/questionnaire-root/app-questionnaire/div/div/app-fit-data-rs/div/div/div/div/div[2]/div[2]/div/app-array-slider-input/div/div/span[6]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dressText dressTextNonSelected</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mm-0&quot;)/div[1]/div[@class=&quot;cointainer&quot;]/questionnaire-root[1]/app-questionnaire[@class=&quot;ng-tns-c9-0 ng-star-inserted&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;inner-content ng-trigger ng-trigger-routerAnimations&quot;]/app-fit-data-rs[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;questionnaire-page&quot;]/div[@class=&quot;scroll-holder&quot;]/div[@class=&quot;swiper-container scroll-field&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide questionnaire-content ng-star-inserted&quot;]/div[2]/div[@class=&quot;slider ng-star-inserted&quot;]/app-array-slider-input[1]/div[@class=&quot;input-row ng-star-inserted&quot;]/div[@class=&quot;dressSizes&quot;]/span[@class=&quot;dressSize ng-star-inserted&quot;]/span[@class=&quot;dressText dressTextNonSelected&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//main[@id='mm-0']/div/div/questionnaire-root/app-questionnaire/div/div/app-fit-data-rs/div/div/div/div/div[2]/div[2]/div/app-array-slider-input/div/div/span[6]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops'])[4]/following::span[12]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tell us your sizes'])[1]/following::span[12]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XXS'])[1]/preceding::span[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XS'])[1]/preceding::span[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//span[6]/span</value>
   </webElementXpaths>
</WebElementEntity>
