<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MicrositeTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f8f9005f-61f0-4c5e-8f8a-7e004b111259</testSuiteGuid>
   <testCaseLink>
      <guid>4e3ec0a7-8ee0-44f1-b05f-a2cdc6144340</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/virtualShowRSVP/createShow</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>e6d9df27-8161-4784-b480-b15b82fe5a87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>867d6186-86d6-4fac-baa1-482e2f4b97e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>94478a58-9183-4a87-9a96-db0bb1d290ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>56a3b13a-2310-4185-9e2e-ea0b1ade2b49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>ed264cfc-9cbb-41ac-afe5-ac849eb0a318</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>c48a746a-1687-41c3-a20b-901820714d98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>9d5870e3-c00b-4b40-b37d-aaf9012a15d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>c5b25a9e-0208-413b-a83e-fc78aa3eec73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>67613932-711f-4f74-a30d-df41d650501c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>38a27d98-9bcf-4ff3-bc92-e09827e33218</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>cbb92a5a-4ae9-4025-b5e2-13cd4942995a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>708ec0d9-d0ec-4409-8062-62015a94640a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>3f6f22b9-28ca-4173-abee-2f0b0dca26a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>ff601af0-7aae-472d-a995-7ef1822bd2f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa4c519a-7f1f-4ff5-b8e1-d156c84d61aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/virtualShowRSVP/micrositeRSVPValidUser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>c10adb6d-84b7-40d9-b4ba-b64d9c4efdf2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>a63056ed-3e9e-4723-82a7-6cdcff67df10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>04caa8a3-694b-4246-97c2-0ec62c70e4c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>f7228926-323e-45c5-aec5-494b9caf63bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>f0f9d641-0a04-421e-8a0e-52b4164178b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>024a188d-516a-4f97-bf11-b440f7ca5394</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>86224a66-4066-493c-9e8b-58d9ce3eb7f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>db9e9cc0-8da0-4e03-95d4-fc1993d90cba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>b529812b-b7c0-486c-83ea-61dc7c761d32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>2d292ce8-301c-4080-8444-68981c7307f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>f309c120-159b-4e62-a33e-e96d8dc6ad57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>4be21a07-59c3-49e2-b211-678de633bf0c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
