<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bottomsRadioButton</name>
   <tag></tag>
   <elementGuidId>698c86a5-862b-4fae-9219-89b237ba3bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mm-0&quot;]/div[2]/div/questionnaire-root/app-questionnaire/div/div[1]/app-questionnaire-my-style-product-rs/div/div/div/div/div[3]/app-my-style-product-question/div/div[4]/div/label/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mm-0&quot;]/div[2]/div/questionnaire-root/app-questionnaire/div/div[1]/app-questionnaire-my-style-product-rs/div/div/div/div/div[3]/app-my-style-product-question/div/div[4]/div/label/div[2]</value>
   </webElementProperties>
</WebElementEntity>
