<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cityInfo</name>
   <tag></tag>
   <elementGuidId>2d10300b-1fa7-49f7-b59a-82c36284d44d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='fix-line-height']/input[following-sibling::label[text()='city']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='fix-line-height']/input[following-sibling::label[text()='city']]</value>
   </webElementProperties>
</WebElementEntity>
