<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dressessRadioButton</name>
   <tag></tag>
   <elementGuidId>64e3eddb-65c6-4ee3-9bcf-2a281eec6efa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mm-0&quot;]/div[2]/div/questionnaire-root/app-questionnaire/div/div[1]/app-questionnaire-my-style-product-rs/div/div/div/div/div[5]/app-my-style-product-question/div/div[1]/div/label/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mm-0&quot;]/div[2]/div/questionnaire-root/app-questionnaire/div/div[1]/app-questionnaire-my-style-product-rs/div/div/div/div/div[5]/app-my-style-product-question/div/div[1]/div/label/div[2]</value>
   </webElementProperties>
</WebElementEntity>
