<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gotItThanks</name>
   <tag></tag>
   <elementGuidId>f3a02885-e253-4497-a28c-1743a8dbdd67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;page-&quot;]/div[8]/div/div/div/find-my-stylist/div/meet-stylist/div/form/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;page-&quot;]/div[8]/div/div/div/find-my-stylist/div/meet-stylist/div/form/div[3]/button</value>
   </webElementProperties>
</WebElementEntity>
