<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rsFirstNametextbox</name>
   <tag></tag>
   <elementGuidId>21dc6787-ce35-49c2-8799-0da8aea7c0f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//custom-input[@name='firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//custom-input[@name='firstName']</value>
   </webElementProperties>
</WebElementEntity>
