<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saveChangesButton</name>
   <tag></tag>
   <elementGuidId>5636c24e-298f-4e28-a20c-cf75cb03fcec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;page-profile&quot;]/div[2]/unsaved-changes-component/div/div[2]/div[2]/button[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;page-profile&quot;]/div[2]/unsaved-changes-component/div/div[2]/div[2]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
