<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sweatersRadioButton</name>
   <tag></tag>
   <elementGuidId>5df6826a-34e3-4c31-98eb-f5627a7c4e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mm-0&quot;]/div/div/questionnaire-root/app-questionnaire/div/div[1]/app-questionnaire-my-style-product-rs/div/div/div/div/div[2]/app-my-style-product-question/div/div[3]/div/label/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mm-0&quot;]/div/div/questionnaire-root/app-questionnaire/div/div[1]/app-questionnaire-my-style-product-rs/div/div/div/div/div[2]/app-my-style-product-question/div/div[3]/div/label/div[2]</value>
   </webElementProperties>
</WebElementEntity>
