<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>topsRadiobutton</name>
   <tag></tag>
   <elementGuidId>c37c787d-bc2e-4587-a59e-54c37c9a9af2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mm-0&quot;]/div/div/questionnaire-root/app-questionnaire/div/div[1]/app-questionnaire-my-style-product-rs/div/div/div/div/div[1]/app-my-style-product-question/div/div[3]/div/label/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mm-0&quot;]/div/div/questionnaire-root/app-questionnaire/div/div[1]/app-questionnaire-my-style-product-rs/div/div/div/div/div[1]/app-my-style-product-question/div/div[3]/div/label/div[2]</value>
   </webElementProperties>
</WebElementEntity>
