<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectSize2</name>
   <tag></tag>
   <elementGuidId>89f5874b-e38f-408d-94b2-d0bdef647b19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='sizeSelect_1']/option[@value='L']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='sizeSelect_1']/option[@value='L']</value>
   </webElementProperties>
</WebElementEntity>
